// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "evento_microservices/user/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	ShowEventEndpoint   endpoint.Endpoint
	AttendEventEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.UserService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		AttendEventEndpoint: MakeAttendEventEndpoint(s),
		ShowEventEndpoint:   MakeShowEventEndpoint(s),
	}
	for _, m := range mdw["ShowEvent"] {
		eps.ShowEventEndpoint = m(eps.ShowEventEndpoint)
	}
	for _, m := range mdw["AttendEvent"] {
		eps.AttendEventEndpoint = m(eps.AttendEventEndpoint)
	}
	return eps
}
